version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/php:7.0-browsers
    working_directory: ~/repo
    steps:
      - checkout
      - run: composer self-update
      # Download and cache dependencies
      - restore_cache:
          keys:
          - composer-{{ checksum "composer.json" }}
          # fallback to using the latest cache if no exact match is found
          - composer-
      - run: composer install -n --prefer-dist
      - save_cache:
          paths:
            - ./vendor
          key: composer-{{ checksum "composer.json" }}
      # - ./bin/phpunit
  deploy:
    docker:
      - image: circleci/python:2.7
    steps:
      - checkout
      - run: pip install ansible
      - run: pip install --upgrade setuptools
      - run: ansible-playbook -i .circleci/inventory -e .circleci/playbook.yml

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master